name: Flake auto-update

on:
  schedule:
    - cron: '0 3 * * 1'  # Runs every Monday at 3 AM UTC
  workflow_dispatch:     # Manual trigger option

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v22

      - name: Update flake.lock
        run: nix flake update

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add flake.lock
          git commit -m "chore: auto-update flake.lock" || echo "No changes to commit"
      
      - name: Push to repo
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
